const TIPO_INSTRUCCION={
    PRINT: 'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    DE_METODO: 'DEC_METODO',
    EXEC: 'EXEC',
    LLAMADA_METODO: 'LLAMADA_METODO',
    IF: 'IF'
}

module.exports = TIPO_INSTRUCCION