const TIPO_VALOR={
    INT: 'VAL_INT',
    BOOLEAN: 'VAL_BOOLEAN',
    DOUBLE: 'VAL_DOUBLE',
    CHAR: 'VAL_CHAR',
    STRING: 'VAL_STRING',
    IDENTIFICADOR: 'VAL_IDENTIFICADOR'
}

module.exports = TIPO_VALOR