const TIPO_INSTRUCCION={
    PRINT: 'INST_PRINT',
    DECLARACION: 'INST_DECLARACION',
    ASIGNACION: 'ASIGNACION',
    WHILE: 'WHILE',
    DOWHILE: 'DOWHILE',
    DE_METODO: 'DEC_METODO',
    EXEC: 'EXEC',
    LLAMADA_METODO: 'LLAMADA_METODO',
    IF: 'IF',
    FOR: 'FOR',
    BREAK: 'BREAK',
    IFELSE: 'IFELSE',
    IFCELSEIF: 'IFCELSEIF',
    ELSEIF: 'ELSEIF',
    CCASES: 'CCASES',
    CASE: 'CASE',
    SWDEFAULT: 'SWDEFAULT'
}

module.exports = TIPO_INSTRUCCION